export const personal = {
  name: "Megha Bairwal",
  title: "Data Strategy Analyst",
  subtitle: "Data engineer at heart. AI enthusiast. Building with data in NYC real estate.",
  email: "meghabairwal@gmail.com",
  linkedin: "https://www.linkedin.com/in/megha-bairwal/",
}

export const journeyStops = [
  {
    id: "california",
    name: "California",
    label: "Where I was born",
    detail: "Born in California. Moved to India at age 1 — so technically a California native, even if just briefly.",
    coordinates: [-119.4179, 36.7783] as [number, number],
    emoji: "🌴",
    period: "Born here",
    color: "#E8956D",
    labelAnchor: "middle" as const,
    labelDy: -16,
  },
  {
    id: "india",
    name: "Gurgaon, India",
    label: "Where I grew up",
    detail: "Grew up here; started coding in the 7th grade. India taught me how to think laterally, move fast, and find patterns in everything.",
    coordinates: [77.0266, 28.4595] as [number, number],
    emoji: "🇮🇳",
    period: "Childhood – 2019",
    color: "#FF9933",
    labelAnchor: "middle" as const,
    labelDy: -16,
  },
  {
    id: "michigan",
    name: "Ann Arbor, MI",
    label: "University of Michigan",
    detail: "Double B.S. in Computer Science and Cognitive Science. GPA 3.76, Dean's list. Fell in love with data, built things, found my direction.",
    coordinates: [-83.743, 42.2808] as [number, number],
    emoji: "〽️",
    period: "2019 – 2023",
    color: "#FFCB05",
    labelAnchor: "middle" as const,
    labelDy: -16,
  },
  {
    id: "denmark",
    name: "Copenhagen",
    label: "Study Abroad",
    detail: "A semester that expanded how I see the world. Copenhagen pushed me to think beyond American defaults — about cities, systems, design, and how different societies solve the same problems differently.",
    coordinates: [12.5683, 55.6761] as [number, number],
    emoji: "🇩🇰",
    period: "2022",
    color: "#C60C30",
    labelAnchor: "middle" as const,
    labelDy: -16,
  },
  {
    id: "dc",
    name: "Washington D.C.",
    label: "Fannie Mae",
    detail: "First real job. Joined a Master Data Management team as a Data Engineer. Built pipelines that actually mattered.",
    coordinates: [-77.0369, 38.9072] as [number, number],
    emoji: "🏛️",
    period: "2023 – 2025",
    color: "#A78BFA",
    labelAnchor: "end" as const,
    labelDy: 4,
    labelDx: -14,
  },
  {
    id: "nyc",
    name: "New York City",
    label: "My new home!",
    detail: "I <3 NY! Working at a NYC-focused PE firm while falling deeper in love with this city every day.",
    coordinates: [-74.006, 40.7128] as [number, number],
    emoji: "🗽",
    period: "2025 – Present",
    color: "#7CB988",
    labelAnchor: "start" as const,
    labelDy: 4,
    labelDx: 14,
  },
]

export const skills = [
  { name: "Python", category: "language", level: 90 },
  { name: "SQL", category: "language", level: 95 },
  { name: "dbt", category: "transform", level: 85 },
  { name: "BigQuery", category: "cloud", level: 85 },
  { name: "AWS", category: "cloud", level: 75 },
  { name: "Looker", category: "viz", level: 85 },
  { name: "Airbyte", category: "pipeline", level: 90 },
  { name: "Airtable", category: "tools", level: 90 },
  { name: "HubSpot", category: "tools", level: 80 },
  { name: "REST APIs", category: "tools", level: 85 },
  { name: "Git", category: "tools", level: 90 },
  { name: "AI / LLMs", category: "ai", level: 80 },
]

export const skillCategories: Record<string, { label: string; color: string }> = {
  language: { label: "Languages", color: "#C4956A" },
  transform: { label: "Transform", color: "#7CB988" },
  cloud: { label: "Cloud", color: "#6B9BAF" },
  viz: { label: "Visualization", color: "#B47EC4" },
  pipeline: { label: "Pipelines", color: "#E8A87C" },
  tools: { label: "Tools", color: "#A8C5A0" },
  ai: { label: "AI / ML", color: "#F0C674" },
}

export const experience = [
  {
    company: "Maverick Real Estate Partners",
    role: "Data Strategy Analyst",
    period: "Sep 2025 – Present",
    location: "New York, NY",
    type: "Private Equity · NYC CRE",
    description:
      "Member of a data strategy team at a PE firm focused on distressed commercial real estate, supporting acquisition, litigation, and portfolio strategy across $1B+ in NYC multifamily and mixed-use assets.",
    highlights: [
      "Built 20+ dbt models and BigQuery transformations powering firm-wide Looker dashboards used daily by investment and legal teams for asset performance, loan exposure, and market analytics",
      "Led end-to-end financial analysis for an active litigation effort — structured data from 1,000+ bank statements to trace $500M+ in inter-entity flows and identify new discovery targets",
      "Led diligence on third-party CMBS data across ~$200B in NYC originations, driving vendor schema improvements prior to ingestion",
      "Integrated 2 new public datasets to classify ~$8B in agency debt and improve rent-regulated asset accuracy",
      "Delivered model enhancements improving foreclosure, rent regulation, and zoning logic, increasing valuation accuracy by ~20%",
      "Designed Vertex AI prototypes for document processing and geocoding to inform future automation workflows",
    ],
    color: "#C4956A",
  },
  {
    company: "Fannie Mae",
    role: "Data Engineer",
    period: "Jun 2023 – Aug 2025",
    location: "Washington, D.C.",
    type: "GSE · Master Data Management",
    description:
      "Built and maintained data infrastructure on the Master Data Management team, processing millions of records daily across a $3T single-family mortgage portfolio.",
    highlights: [
      "Developed 20+ AWS Lambda functions integrating 10+ financial data sources, processing millions of records per day",
      "Built and maintained 30+ ETL workflows supporting downstream reporting used by 8+ business teams",
      "Standardized naming conventions and applied record matching logic across 100M+ records across 20+ data sources",
      "Led 6+ production ETL deployments coordinating releases with cross-functional teams across dev, test, and prod",
      "Built a GAN-based synthetic data generator producing realistic test records while preserving privacy and compliance",
      "Mapped business requirements for an in-house alternative to TIBCO BWCE, projected to cut operational costs by 30%",
    ],
    color: "#7CB988",
  },
  {
    company: "GRIP Lab, University of Michigan",
    role: "Junior Programmer & Researcher",
    period: "Sep 2021 – May 2024",
    location: "Ann Arbor, MI",
    type: "Academic Research · EdTech",
    description:
      "Co-founded and led deployment of Anotemos, a web-based video annotation platform, across 6 language classrooms in partnership with faculty.",
    highlights: [
      "Built and shipped 30+ product features in a 2-person engineering team using Angular, JavaScript, MeteorJS, and HTML/CSS",
      "Drove adoption across 10+ university stakeholders, producing onboarding materials and video tutorials to support rollout",
      "Resolved ~50% of platform bugs, improving stability during live classroom use",
      "First author of a paper presented at the SITE conference (Las Vegas, 2024) on interactive multimedia in education",
    ],
    color: "#6B9BAF",
  },
]

export const projects = [
  {
    title: "Simplingo",
    description: "An AI browser extension that simplifies technical documents and translates between languages in real time. Flask backend powered by Google Gemini, OpenAI, and Hugging Face models.",
    tags: ["TypeScript", "Python", "Flask", "Gemini", "OpenAI", "Browser Extension"],
    github: "https://github.com/yum25/simplingo",
    article: null,
    placeholder: false,
  },
  {
    title: "News Headline Generator",
    description: "A recurrent neural network trained to generate news headlines in the distinct styles of CNN, BuzzFeed, NYT, Reuters, and Fox News. An early deep dive into language modeling and style transfer.",
    tags: ["Python", "RNN", "NLP", "Deep Learning"],
    github: "https://github.com/meghabairwal/NewsHeadlineGenerator",
    article: "https://medium.com/@emily.gelchie/using-neural-networks-to-generate-news-titles-e0e7c0c59bcd",
    placeholder: false,
  },
  {
    title: "Lyric Generator",
    description: "A language model trained on 1M+ songs that generates original lyrics mimicking the styles of multiple artists. Built to explore how neural networks capture voice, rhythm, and pattern.",
    tags: ["Python", "LLM", "NLP", "Jupyter"],
    github: "https://github.com/meghabairwal/LyricGenerator",
    article: null,
    placeholder: false,
  },
]

export const publications = [
  {
    title: "Multimedia Annotation: Promoting Constructivist Interactions about Content in Education",
    authors: "Megha Bairwal, Patricio Herbst, Carolyn Hetrick",
    venue: "Society for Information Technology & Teacher Education (SITE) International Conference",
    location: "Las Vegas, NV",
    year: "2024",
    type: "Conference Paper",
    description: "Used lenses of constructivism and cognitive theory in multimedia learning to analyze how 92 introductory German language students engaged with video annotation technology. Preliminary analyses suggest multimedia technology corresponded with improved learning quality and constructivist classroom engagement.",
    link: "https://www.learntechlib.org/p/224082/",
    color: "#6B9BAF",
  },
  {
    title: "NYC Distressed Real Estate Markets & Rent-Stabilized Asset Performance",
    authors: "Megha Bairwal et al., Maverick Real Estate Partners",
    venue: "White Paper",
    location: "New York, NY",
    year: "2025",
    type: "White Paper",
    description: "Co-authored analysis of distressed commercial real estate conditions in New York City, with a focus on rent-stabilized multifamily asset performance, market dynamics, and investment implications.",
    link: null,
    color: "#C4956A",
  },
]

export const terminalLines = [
  { text: "whoami", delay: 300, isCommand: true },
  { text: "Megha Bairwal", delay: 900, isCommand: false },
  { text: "cat current_role.txt", delay: 1700, isCommand: true },
  { text: "Data Strategy Analyst @ Maverick Real Estate Partners, NYC", delay: 2300, isCommand: false },
  { text: "echo $PASSION", delay: 3100, isCommand: true },
  { text: "data engineering + AI + building things that matter", delay: 3700, isCommand: false },
  { text: "cat currently_reading.txt", delay: 4500, isCommand: true },
  { text: "Tomorrow, and Tomorrow, and Tomorrow", delay: 5100, isCommand: false },
  { text: "cat reading_goal.txt", delay: 5900, isCommand: true },
  { text: "2026: [████░░░░░░░░░░░] 4/15 books", delay: 6500, isCommand: false },
  { text: "echo $OFFLINE", delay: 7300, isCommand: true },
  { text: "running long distances + reading fiction", delay: 7900, isCommand: false },
]
